{
 "title": "Terry",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(terry_users_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(terry_users_total{instance=~\"$instance\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(terry_users_logged_total{instance=~\"$instance\"})",
     "legendFormat": "Logged in"
    },
    {
     "expr": "sum(terry_users_submitted_total{instance=~\"$instance\"})",
     "legendFormat": "Submitted"
    },
    {
     "expr": "sum(terry_users_non_zero_total{instance=~\"$instance\"})",
     "legendFormat": "Non zero score"
    }
   ]
  },
  {
   "title": "Logged",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(terry_users_logged_total{instance=~\"$instance\"})",
     "legendFormat": "Logged users"
    },
    {
     "expr": "sum(terry_users_logged_total{instance=~\"$instance\"}) / sum(terry_users_total{instance=~\"$instance\"})",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Submissions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(terry_submissions_total{instance=~\"$instance\"}) by (task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Submissions per task",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(terry_submissions_total{instance=~\"$instance\"}) by (task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Submitted",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(terry_users_submitted_total{instance=~\"$instance\"})",
     "legendFormat": "Submitted users"
    },
    {
     "expr": "sum(terry_users_submitted_total{instance=~\"$instance\"}) / sum(terry_users_logged_total{instance=~\"$instance\"})",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Score > 0",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(terry_users_non_zero_total{instance=~\"$instance\"})",
     "legendFormat": "Submitted users"
    },
    {
     "expr": "sum(terry_users_non_zero_total{instance=~\"$instance\"}) / sum(terry_users_submitted_total{instance=~\"$instance\"})",
     "legendFormat": "%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(terry_submissions_total{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node\",mode=\"idle\",instance=~\"$instance\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(terry_sources_lang_total{instance=~\"$instance\"}) by (language))",
     "legendFormat": "{{language}}"
    }
   ]
  },
  {
   "title": "Submissions per language",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(terry_sources_lang_total{instance=~\"$instance\"}) by (language)",
     "legendFormat": "{{language}}"
    }
   ]
  },
  {
   "title": "Submission rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "60 * sum(rate(terry_submissions_total{instance=~\"$instance\"}[5m])) by (task)",
     "legendFormat": "{{task}}"
    },
    {
     "expr": "60 * sum(rate(terry_submissions_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "I/O files and Submissions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(terry_inputs_generated_total{instance=~\"$instance\"})",
     "legendFormat": "Generated inputs"
    },
    {
     "expr": "sum(terry_outputs_uploaded_total{instance=~\"$instance\"})",
     "legendFormat": "Uploaded outputs"
    },
    {
     "expr": "sum(terry_sources_uploaded_total{instance=~\"$instance\"})",
     "legendFormat": "Uploaded sources"
    },
    {
     "expr": "sum(terry_submissions_total{instance=~\"$instance\"})",
     "legendFormat": "Submissions"
    }
   ]
  },
  {
   "title": "Maximum score per task",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(terry_tasks_max_score{instance=~\"$instance\"}) by (task)",
     "legendFormat": "{{task}}"
    }
   ]
  }
 ]
}