name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo install sqlx-cli 
      - run: sqlx database create
        working-directory: ./backend
      - run: sqlx migrate run
        working-directory: ./backend
      - run: cargo test
        working-directory: ./backend
